### ISSUE TITLE
Fix build error with x86

### ISSUE THREAD

**Issue by MggMuggins** [redox-os/orbutils#36]
Because of this section in Cargo.toml
```toml
[target.'cfg(target_os = "redox")'.dependencies]
redox_event = { git = "https://github.com/redox-os/event.git" }
redox_syscall = "0.1"
```
This crate doesn't build on x86. It isn't supposed to either, but since Jenkins is set up with this repo, wouldn't it be nice for that to be accurate?
